package it.unibs.ingsoft.domain.validation;

public enum ValidationErrorCode {
    CAMPO_OBBLIGATORIO_MANCANTE,
    NUMERO_PARTECIPANTI_NON_INTERO,
    NUMERO_PARTECIPANTI_NON_POSITIVO,
    TERMINE_ISCRIZIONE_NON_FUTURO,
    DATA_EVENTO_TROPPO_PRESTO,
    DATA_CONCLUSIVA_PRECEDENTE,
    TIPO_INTERO_NON_VALIDO,
    TIPO_DECIMALE_NON_VALIDO,
    TIPO_DATA_NON_VALIDA,
    TIPO_ORA_NON_VALIDA,
    TIPO_BOOLEANO_NON_VALIDO
}
