package it.unibs.ingsoft.domain.error;

public enum DomainErrorCode {
    NULL_PROPOSTA_CATEGORY,
    NULL_STATO_PROPOSTA,
    INVALID_STATE_TRANSITION,
    PROPOSTA_NOT_SALVABILE,
    PROPOSTA_NOT_VALID_FOR_PUBLICATION,
    PROPOSTA_PUBLICATION_DEADLINE_EXPIRED,
    PROPOSTA_NOT_WITHDRAWABLE,
    PROPOSTA_WITHDRAWAL_TOO_LATE,
    PROPOSTA_NOT_OPEN_FOR_SUBSCRIPTION,
    PROPOSTA_SUBSCRIPTION_DEADLINE_EXPIRED,
    PROPOSTA_ALREADY_SUBSCRIBED,
    PROPOSTA_FULL,
    PROPOSTA_NOT_OPEN_FOR_UNSUBSCRIPTION,
    PROPOSTA_UNSUBSCRIPTION_DEADLINE_EXPIRED,
    PROPOSTA_NOT_SUBSCRIBED,
    PROPOSTA_FIELDS_NOT_MODIFIABLE,
    PROPOSTA_PARTICIPANTS_MISSING,
    PROPOSTA_PARTICIPANTS_NOT_POSITIVE,
    PROPOSTA_PARTICIPANTS_NOT_INTEGER
}
